### ISSUE TITLE
Policy "CMP0048" is not known to this version of CMake.

### ISSUE THREAD

**Issue by PHHargrove** [Intrepid/llvm-upc#16]
I am getting the error shown in issue title on a Ubuntu Trusty system with cmake 2.8.12.2.
Is there a new minimum version on CMake required?

-Paul

**Comment by swatanabe** [comment]
AMDG

On 05/03/2016 12:51 PM, Paul H. Hargrove wrote:
> I am getting the error shown in issue title on a Ubuntu Trusty system with cmake 2.8.12.2.
> Is there a new minimum version on CMake required?
> 

No.  This was introduced by:
https://github.com/Intrepid/clang-upc/commit/493b08c6904c3b42c290b0007721a6ef90920e0f

In Christ,
Steven Watanabe

**Comment by PHHargrove** [comment]
Steven,

I am not sure I understand.

The CMake docs I found say "This policy was introduced in CMake version 3.0.".
So the commit you reference would require a minimum CMake version of 3.0, right?

Are you planning revert (or modify) that commit?
If not, then the `cmake_minimum_required` needs to change to 3.0, if I understand correctly.

I am sure I can build CMake-3.0 on all of my systems, but would really rather not if it isn't necessary.

-Paul

**Comment by PHHargrove** [comment]
Nevermind my (now deleted) previous comment.
Steven fixed the isuse while I was typing it.

**Comment by PHHargrove** [comment]
Works now.
Thanks.
