### ISSUE TITLE
Solaris: wrong gcc install selected

### ISSUE THREAD

**Issue by PHHargrove** [Intrepid/llvm-upc#18]
Clang uses gcc's installation to find ctrbegin.o and crtend.o.
With my builds on Solaris, however, something is going wrong with the logic that should be finding the gcc install, and so executables cannot link:
```
$ /export/home/phargrov/upcnightly-64/llvm-upc/bin/clang hello.c -v 2>&1 | cat -n
     1  clang version 3.8.0  (UPC 3.8.1-0 20160504) 
     2  Target: x86_64-pc-solaris2.11
     3  Thread model: posix
     4  InstalledDir: /export/home/phargrov/upcnightly-64/llvm-upc/bin
     5  Found candidate GCC installation: /usr/gcc/4.5
     6  Found candidate GCC installation: /usr/gcc/4.8
     7  Selected GCC installation: /usr/gcc/4.5/lib/gcc/sparc-sun-solaris2.11
     8   "/export/home/phargrov/upcnightly-64/llvm-upc/bin/clang" -cc1 -triple x86_64-pc-solaris2.11 -emit-obj -mrelax-all -disable-free -main-file-name hello.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -target-cpu x86-64 -target-linker-version 2.23.1 -v -dwarf-column-info -debugger-tuning=gdb -resource-dir /export/home/phargrov/upcnightly-64/llvm-upc/bin/../lib/clang/3.8.0 -fdebug-compilation-dir /export/home/phargrov -ferror-limit 19 -fmessage-length 0 -fno-use-cxa-atexit -fobjc-runtime=gcc -fdiagnostics-show-option -o /var/tmp/hello-ba780b.o -x c hello.c
     9  clang -cc1 version 3.8.0 based upon LLVM 3.8.0 default target x86_64-pc-solaris2.11
    10  ignoring nonexistent directory "/usr/local/include"
    11  #include "..." search starts here:
    12  #include <...> search starts here:
    13   /export/home/phargrov/upcnightly-64/llvm-upc/bin/../lib/clang/3.8.0/include
    14   /usr/include
    15  End of search list.
    16   "/usr/bin/ld" -C -e _start -Bdynamic --dynamic-linker /usr/lib/amd64/ld.so.1 -o a.out /usr/lib/amd64/crt1.o /usr/lib/amd64/crti.o /usr/lib/amd64/values-Xa.o crtbegin.o -L/export/home/phargrov/upcnightly-64/llvm-upc/bin -L/export/home/phargrov/upcnightly-64/llvm-upc/bin/../lib -L/usr/lib/amd64/ /var/tmp/hello-ba780b.o -lgcc_s -lc -lgcc -lm crtend.o /usr/lib/amd64/crtn.o
    17  ld: fatal: file crtbegin.o: open failed: No such file or directory
    18  ld: fatal: library -lgcc: not found
    19  ld: fatal: file crtend.o: open failed: No such file or directory
    20  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Notice that line 2 has correctly identified the target, and lines 5 and 6 correctly locate candidate gcc installations.
However, line 7 shows that Clang has appended en entirely wrong target triple.
The resulting "Selected GCC Installation" does not exist.

If I create a symlink from the incorrectly selected GCC install to the proper one, then full paths are used for crt{begin,end}.o in link command and (almost) everything works.
However, this is a multilib system and so the symlink approach can only fix either the -m32 or -m64 target, not both.

This was not happening prior to the 3.8 merge, FWIW.

-Paul

**Comment by swatanabe** [comment]
AMDG

On 05/05/2016 10:52 AM, Paul H. Hargrove wrote:
> Clang uses gcc's installation to find ctrbegin.o and crtend.o.
> With my builds on Solaris, however, something is going wrong with the logic that should be finding the gcc install, and so executables cannot link:
> 
> 

Does this also happen with upstream clang?

In Christ,
Steven Watanabe

**Comment by swatanabe** [comment]
AMDG

  Can you work around the problem with
--with-gcc-toolchain=... (for configure)
or --gcc-toolchain=... (on the clang command
line)?

In Christ,
Steven Watanabe

**Comment by swatanabe** [comment]
AMDG

On 05/05/2016 10:52 AM, Paul H. Hargrove wrote:
> 
>      2  Target: x86_64-pc-solaris2.11
>      7  Selected GCC installation: /usr/gcc/4.5/lib/gcc/sparc-sun-solaris2.11

This seems to be hard-coded at ToolChains.cpp:1512 ff.

In Christ,
Steven Watanabe

**Comment by swatanabe** [comment]
AMDG

It was probably broken by this:

commit ce8ac555c91db9ab40638d092ce3fb09f1859245
Author: Rafael Espindola <rafael.espindola@gmail.com>
Date:   Mon Aug 31 19:17:51 2015 +0000

    Stop hardcoding GCC paths in crt/ld.so lookup.

    This patch refactors the code to use the GCC installation detector
    (modified so that it works in Solaris), and uses
    ToolChain::GetFilePath everywhere once it works.

    Patch by Xan López <xan@igalia.com>!

    git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@246473
91177308-0d34

In Christ,
Steven Watanabe

**Comment by PHHargrove** [comment]
The released clang 3.8.0 exhibits the same problem.


I tried the following: 
- --gcc-toolchain=/usr/gcc/4.5
- --gcc-toolchain=/usr/gcc/4.5/lib/
- --gcc-toolchain=/usr/gcc/4.5/lib/gcc
- --gcc-toolchain=/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/
- --gcc-toolchain=/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2

The link fails as before and the only visible difference is the lack of "Candidate GCC Installation" and "Selected GCC Installation" lines in the "-v" output.

**Comment by swatanabe** [comment]
AMDG

  Here's my best attempt a fixing it.  I don't
know what the correct path for x86_64 is, so
that most likely still needs to be added.

In Christ,
Steven Watanabe

**Comment by PHHargrove** [comment]
Steven,

You say "Here's by best attempt..." but I see no attachment and no new commits.

The path for x86_64 is to append "amd64":
```
$ find /usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2 -name '*.o'
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/amd64/gmon.o
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/amd64/crtbegin.o
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/amd64/crtend.o
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/crtbegin.o
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/crtend.o
/usr/gcc/4.5/lib/gcc/i386-pc-solaris2.11/4.5.2/gmon.o
```

**Comment by swatanabe** [comment]
AMDG

On 05/05/2016 12:59 PM, Paul H. Hargrove wrote:
> Steven,
> 
> You say "Here's by best attempt..." but I see no attachment and no new commits.
> 

  github does seem to like attachments.

In Christ,
Steven Watanabe

**Comment by PHHargrove** [comment]
Steven,

I got the attachment in email now.
However, I have been looking at the logic in Generic_GCC::GCCInstallationDetector::scanLibDirForGCCTripleSolaris() I think I see the true source of the problem.

The issue is that the loop tries to avoid visiting the same directory more than once, but doesn't consider the triple suffix when doing so.  As a result the first call to scanLibDirForGCCTripleSolaris() with the "sparc" value for CandidateTriple marks /usr/gcc/4.5 and /usr/gcc/4.8 as already tried.  Then the second call with the *correct* triple skips those directories.

I am looking at the right way to fix this, but a preliminary 1-line change seems to work:
```
--- src/tools/clang/lib/Driver/ToolChains.cpp~  Thu May  5 12:44:48 2016
+++ src/tools/clang/lib/Driver/ToolChains.cpp   Thu May  5 12:45:46 2016
@@ -2208,7 +2208,11 @@

     if (CandidateVersion.Major != -1) // Filter obviously bad entries.
       if (!CandidateGCCInstallPaths.insert(LI->getName()).second)
+#if 0   
         continue; // Saw this path before; no need to look at it again.
+#else
+        {/*empty*/} // Do NOT skip, since CandidateTriple may be different than previous attempt
+#endif
     if (CandidateVersion.isOlderThan(4, 1, 1))
       continue;
     if (CandidateVersion <= Version)
```

The variable name SolarisSPARCTriples should probably eventually be changed to "SolarisTriples" or replaced by logic like in you patch.  However, I think my fix is needed anyway if that list could ever contain more than 1 element (as is certainly the case for others).

-Paul

**Comment by PHHargrove** [comment]
Steven,

I am working now on a patch that combines yours with the logic require to append "amd64/" or "sparcv9/" as appropriate.  I will also incorporate an improved version of my simple patch (previous comment) so that the case of multiple candidate triples will work (even though your changes do reduce the candidate lists to 1 element).

I expect to have a pull request for your review some time later today.

-Paul

**Comment by PHHargrove** [comment]
It works!
I will clean-up my code and produce a pull request now.

-Paul
